version: '3.8'

services:
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      volumes:
        - ./database:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
    redisservice:
      image: redis
      container_name: redisservice
    backend:
      build: ./backend
      ports:
        - 8080:8080
      environment:
        - PORT=8080
        - REQUEST_ORIGIN=http://localhost
        - REDIS_HOST=redisservice
        - POSTGRES_HOST=postgres
    frontend:
      build: ./frontend
      ports:
        - 5000:5000