version: '3.8'

services:
    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
    redisservice:
      image: redis
      build: .
      container_name: redisservice
    backend:
      image: backend
      build: .
      command: ./server
      container_name: backend26
      ports:
        - 127.0.0.1:8080:8080
      environment:
        - PORT=8080
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redisservice
        - POSTGRES_HOST=postgres
    frontend:
      image: frontend
      build: .
      command: ["serve","-s", "-l", "5000", "build"]
      container_name: frontend26
      ports:
        - 127.0.0.1:5000:5000