version: '3.8'

services:
    backend:
      image: backend
      build: .
      command: ./server
      container_name: backend23
      ports:
        - 127.0.0.1:8080:8080
      environment:
        - PORT=8080
        - REQUEST_ORIGIN=http://localhost:5000
    frontend:
      image: frontend
      build: .
      command: ["serve","-s", "-l", "5000", "build"]
      container_name: frontend23
      ports:
        - 127.0.0.1:5000:5000