version: '3.8'

services:
    backend:
      image: backend
      build: .
      container_name: backend23
      ports:
        - 8080:8080
      environment:
        - PORT=8080
        - REQUEST_ORIGIN=http://localhost:5000
    frontend:
      image: frontend
      build: .
      container_name: frontend23
      ports:
        - 5000:5000