version: '3.8'

services:

    twentyTwo:
      image: devopsdockeruh/simple-web-service
      build: .
      command: server
      volumes:
        - ./txt.log:/usr/src/app/text.log
      container_name: twentyTwo
      ports:
        - 5555:8080